name: Sync Gitee to subfolder and unzip to master

on:
  schedule:
    - cron: '0 16 */2 * *'  # 每两天北京时间 00:00 运行
  workflow_dispatch:         # 支持手动运行

jobs:
  sync_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create gitee-source folder and clean it
        run: |
          mkdir -p gitee-source
          rm -rf gitee-source/*

      - name: Download Gitee repo ZIP and extract to gitee-source/
        run: |
          wget -O gitee.zip https://gitee.com/PizazzXS/another-d/repository/archive/master.zip
          unzip gitee.zip
          cp -r another-d-master/* gitee-source/
          rm -rf another-d-master gitee.zip

      - name: Commit to sync-from-gitee branch
        run: |
          git checkout -B sync-from-gitee
          git add gitee-source/
          git commit -m "Sync Gitee project to gitee-source/" || echo "No changes"
          git push origin sync-from-gitee --force

      - name: Unzip ZIP files in gitee-source/
        run: |
          cd gitee-source
          if [ -f "单线路.zip" ]; then unzip -o "单线路.zip"; fi
          if [ -f "多线路.zip" ]; then unzip -o "多线路.zip"; fi
          cd ..
          git add gitee-source/
          git commit -m "解压 ZIP 到 gitee-source 子目录（保留 ZIP）" || echo "No changes"
          git push origin sync-from-gitee --force

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-from-gitee
          title: "🔄 同步 Gitee 更新到 master"
          body: |
            此 PR 由 GitHub Actions 自动创建，用于同步 Gitee 仓库的最新内容并解压 ZIP 文件。
          commit-message: "同步 Gitee 并解压 ZIP 文件"
          base: master
          delete-branch: true  # ✅ PR 合并后自动删除临时分支

      - name: Enable auto-merge for PR
        if: steps.cpr.outputs.pull-request-url != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

  cleanup_runs:
    runs-on: ubuntu-latest
    needs: sync_and_pr
    steps:
      - name: Delete old workflow runs, keep last 10
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 10
