
name: Sync Gitee to subfolder and unzip to master

on:
  schedule:
    - cron: '0 16 */2 * *'  # 每两天北京时间 00:00 运行
  workflow_dispatch:         # 支持手动运行

jobs:
  sync_and_unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create gitee-source folder and clean it
        run: |
          mkdir -p gitee-source
          rm -rf gitee-source/*

      - name: Download Gitee repo ZIP and extract to gitee-source/
        run: |
          wget -O gitee.zip https://gitee.com/PizazzXS/another-d/repository/archive/master.zip
          unzip gitee.zip
          cp -r another-d-master/* gitee-source/
          rm -rf another-d-master gitee.zip

      - name: Commit and push to main
        run: |
          git add gitee-source/
          git commit -m "Sync Gitee project to gitee-source/" || echo "No changes"
          git push origin main

      - name: Switch to master branch (create if not exist)
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/master; then
            git switch master
          else
            git checkout -b master
          fi

      - name: Unzip gitee-source 中的指定 ZIP 文件（保留 ZIP）
        run: |
          cd gitee-source
          if [ -f "单线路.zip" ]; then unzip -o "单线路.zip"; fi
          if [ -f "多线路.zip" ]; then unzip -o "多线路.zip"; fi
          cd ..

      - name: Commit and push 解压内容到 master（忽略 .github）
        run: |
          git reset HEAD .github/ || true
          git add gitee-source/
          git commit -m "解压 ZIP 到 gitee-source 子目录（保留 ZIP）" || echo "No changes"
          git push origin master

  cleanup_runs:
    runs-on: ubuntu-latest
    needs: sync_and_unzip
    steps:
      - name: Delete old workflow runs, keep last 10
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 10
