name: Sync Gitee to subfolder and unzip to main

on:
  schedule:
    - cron: '0 16 */2 * *'  # 每两天北京时间 00:00 运行
  workflow_dispatch:

jobs:
  sync_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create gitee-source folder and clean it
        run: |
          mkdir -p gitee-source
          rm -rf gitee-source/*

      - name: Download Gitee repo ZIP and extract to gitee-source/
        run: |
          wget -O gitee.zip https://gitee.com/PizazzXS/another-d/repository/archive/master.zip
          unzip gitee.zip
          cp -r another-d-master/* gitee-source/
          rm -rf another-d-master gitee.zip

      - name: Commit synced content to sync-from-gitee branch
        run: |
          git checkout -B sync-from-gitee
          git add gitee-source/
          git commit -m "Sync Gitee project to gitee-source/" || echo "No changes"
          git push origin sync-from-gitee --force

      - name: 解压 ZIP 文件到子文件夹并提交
        run: |
          cd gitee-source

          unzip_and_track() {
            zip_name="$1"
            dir_name="$2"

            if [ -f "$zip_name" ]; then
              echo "✅ 解压 $zip_name 到 $dir_name/"
              mkdir -p "$dir_name"
              unzip -o "$zip_name" -d "$dir_name/"
              touch "$dir_name/.gitkeep"  # 确保 Git 跟踪目录
            else
              echo "⚠️ $zip_name 不存在，跳过"
            fi
          }

          unzip_and_track "单线路.zip" "单线路"
          unzip_and_track "多线路.zip" "多线路"

          cd ..

          echo "📁 当前目录内容："
          ls -R gitee-source/

          git add gitee-source/
          git status

          git commit -m "将 ZIP 文件解压到指定文件夹（保留 ZIP 文件）" || echo "No changes"
          git push origin sync-from-gitee --force

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-from-gitee
          title: "🔄 同步 Gitee 更新并解压 ZIP 到指定目录"
          body: |
            此 PR 自动从 Gitee 项目同步内容，并将 ZIP 文件解压到指定文件夹：
            - `gitee-source/单线路/`
            - `gitee-source/多线路/`
          commit-message: "同步并解压 ZIP 文件"
          base: main
          delete-branch: true

      - name: Enable auto-merge for PR
        if: steps.cpr.outputs.pull-request-url != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

  cleanup_runs:
    runs-on: ubuntu-latest
    needs: sync_and_pr
    steps:
      - name: Delete old workflow runs, keep last 10
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 10
